---
- name: Prepare single Ubuntu Server for edX Installation
  hosts: all
  user: ubuntu
  sudo: True
  gather_facts: False

  vars:
    # Playbook
    local_conf: False
    config_folder: configuration
    config_repo: https://github.com/edx/configuration.git
    openedx_version: named-release/birch
    # System
    TIMEZONE: Europe/Zurich
    LOCALE: en_GB.UTF-8

  handlers:
    - name: update tzdata
      command: dpkg-reconfigure --frontend noninteractive tzdata
      
    - name: reboot
      command: shutdown -r now 'Rebooting to complete system upgrade'
               removes=/var/run/reboot-required

  tasks:
    - name: Generate locales
      command: locale-gen {{ LOCALE }}

    - name: Set locale
      command: >
        /usr/sbin/update-locale
        LANG={{ LOCALE }}
        LANGUAGE={{ LOCALE }}
        LC_ALL={{ LOCALE }}

    - name: Set /etc/timezone
      template: src=templates/etc/timezone dest=/etc/timezone
      notify: update tzdata

    - name: Update System
      apt: update_cache=yes

    - name: Upgrade System
      apt: upgrade=full
      notify: reboot

    - name: Install packages
      action: apt pkg={{item}} state=installed
      with_items:
      # basics
      - htop
      - unzip
      # security
      - unattended-upgrades
      # edx requirements
      - build-essential
      - software-properties-common
      - python-software-properties
      - curl
      - libxml2-dev
      - libxslt1-dev
      - libfreetype6-dev
      - python-pip
      - python-apt
      - python-dev
      - git-core
      - python-virtualenv 
      - virtualenvwrapper
      - gcc
      - autoconf
      - g++
      - ca-certificates

    - name: Prepare PIP
      shell: sudo pip install --upgrade pip && sudo pip install --upgrade virtualenv && sudo pip install --upgrade virtualenvwrapper 

    - name: Check if directory already exists
      stat: path=/var/tmp/configuration
      register: p

    - name: Remove existing configuration directory
      shell: sudo rm -r /var/tmp/configuration
      when: p.stat.isdir is defined and p.stat.isdir

    - name: Pull Repo - Local
      synchronize: src=../{{ config_folder }} dest=/var/tmp/ recursive=yes
      when: local_conf

    - name: Rename Configuration folder
      shell: mv /var/tmp/{{ config_folder }} /var/tmp/configuration
      when: local_conf

    - name: Pull Repo - Origin
      git: >
        dest=/var/tmp/{{ config_folder }}
        repo={{ config_repo }}
        version={{ openedx_version }}
        accept_hostkey=yes
      when: local_conf == False

    - name: Check if directory already exists
      stat: path=/var/tmp/configuration
      register: check_path

    - name: Rename Configuration folder
      shell: mv /var/tmp/{{ config_folder }} /var/tmp/configuration
      when: check_path.stat.exists == false

    - name: Run requirements file
      pip: chdir=/var/tmp/configuration/ requirements=requirements.txt
